# yamllint configuration - https://yamllint.readthedocs.io

extends: default

rules:
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  document-start:
    present: false

  document-end:
    present: false

  quoted-strings:
    required: only-when-needed

  new-lines:
    type: unix
