alias ls='eza --icons --group-directories-first'
alias ll='eza -l --icons --git'
alias la='eza -la --icons --git'
alias tree='eza -T'

alias cat='bat --paging=never'
alias find='fd'
alias grep='rg'
alias du='dust'
alias df='duf'

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'

# Git
alias g='git'
alias gss='git status -s'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias glr='git pull --rebase'
alias gd='git diff'
alias gdc='git diff --cached'
alias grhh='git reset HEAD --hard'
alias glog='git log --oneline --graph --decorate -20'
alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign -m "--wip-- [skip ci]"'
alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
alias gst='git stash'
alias gsta='git stash push'
alias gstaa='git stash apply'
alias gstall='git stash --all'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show'
alias gsts1='git stash show -p stash@{0}'
alias glg='git log --stat'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glgm='git log --graph --max-count=10'
alias glgp='git log --stat -p'
alias glo='git log --oneline --decorate'
alias glod='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'
alias glods='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'' --date=short'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias glol='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'
alias glola='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --all'
alias glols='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --stat'
alias lg='lazygit'

# Misc
alias c='clear'
alias q='exit'
alias reload='exec $SHELL -l'
alias path='echo $PATH | tr ":" "\n"'
